name: size report

on:
  workflow_run:
    workflows: ['size data']
    types:
      - completed

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  size-report:
    runs-on: ubuntu-latest
    if: >
      github.repository == 'zedom/zedom' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download Size Data
        uses: dawidd6/action-download-artifact@v9
        with:
          name: size-data
          run_id: ${{ github.event.workflow_run.id }}
          path: temp/size

      - name: Read PR Number
        id: pr-number
        uses: juliangruber/read-file-action@v1
        with:
          path: temp/size/number.txt

      - name: Read base branch
        id: pr-base
        uses: juliangruber/read-file-action@v1
        with:
          path: temp/size/base.txt

      - name: Download Previous Size Data
        uses: dawidd6/action-download-artifact@v9
        with:
          branch: ${{ steps.pr-base.outputs.content }}
          workflow: size-data.yml
          event: push
          name: size-data
          path: temp/size-prev
          if_no_artifact_found: warn

      - name: Prepare report
        run: |
          echo "## 📦 Bundle Size Report" > size-report.md
          echo "" >> size-report.md
          echo "### Current Size" >> size-report.md
          echo "\`\`\`" >> size-report.md
          cat temp/size/current.txt >> size-report.md
          echo "\`\`\`" >> size-report.md
          
          if [ -f temp/size-prev/current.txt ]; then
            echo "" >> size-report.md
            echo "### Previous Size" >> size-report.md
            echo "\`\`\`" >> size-report.md
            cat temp/size-prev/current.txt >> size-report.md
            echo "\`\`\`" >> size-report.md
          fi

      - name: Read Size Report
        id: size-report
        uses: juliangruber/read-file-action@v1
        with:
          path: ./size-report.md

      - name: Create Comment
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.pr-number.outputs.content }}
          body: |
            ${{ steps.size-report.outputs.content }}
            <!-- ZEDOM_SIZE -->
          body-include: '<!-- ZEDOM_SIZE -->'